server:
  port: 8081

internal:
  secret:
    key: ${INTERNAL_SECRET_KEY:oO"kdug32^*Pg`9}

booking:
  service_url: ${BOOKING_SERVICE_URL:http://localhost:8085}

user:
  service_url: ${USER_SERVICE_URL:http://localhost:8087}

spring:
  application:
    name: comment-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:123456@localhost:27017/hotel_comments_db?authSource=admin}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
