server:
  port: 8081

internal:
  secret: ${INTERNAL_SECRET:oO"kdug32^*Pg`9}

booking:
  service_url: ${BOOKING_SERVICE_URL:http://localhost:8085}

user:
  service_url: ${USER_SERVICE_URL:http://localhost:8087}

spring:
  application:
    name: comment-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${MONGO_INITDB_ROOT_USERNAME:root}:${MONGO_INITDB_ROOT_PASSWORD:123456}@mongodb:27017/hotel_comments_db?authSource=admin}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
