server:
  port: 8085

internal:
  secret:
    key: oO"kdug32^*Pg`9
hotel:
  service:
    url: http://localhost:8084

spring:
  application:
    name: booking-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: berkantgc
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
