server:
  port: 8080

jwt:
  secret: 4UZslZIUa2bkHgxTGTACDPSKME0MxZDw

internal:
  secret:
    key: oO"kdug32^*Pg`9

management:
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath*:public.pem
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://auth-service:8087}
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**

            - id: comment-service
              uri: ${COMMENT_SERVICE_URL:http://comment-service:8081}
              predicates:
                - Path=/api/v1/comments/**

            - id: notification-service-websocket
              uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8082}
              predicates:
                - Path=/notify/**
              filters:
                - RewritePath=/notify(?<segment>/?.*), $\{segment}

            # REST
            - id: notification-service-http
              uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8082}
              predicates:
                - Path=/api/v1/notifications/**

            - id: hotel-admin
              uri: ${HOTEL_ADMIN_SERVICE_URL:http://hotel-admin-service:8083}
              predicates:
                - Path=/api/v1/admin/**

            - id: hotel-service
              uri: ${HOTEL_SERVICE_URL:http://hotel-service:8084}
              predicates:
                - Path=/api/v1/hotels/**

            - id: booking-service
              uri: ${BOOKING_SERVICE_URL:http://booking-service:8085}
              predicates:
                - Path=/api/v1/bookings/**