server:
  port: 8080

jwt:
  secret: 4UZslZIUa2bkHgxTGTACDPSKME0MxZDw

internal:
  secret:
    key: oO"kdug32^*Pg`9

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath*:public.pem
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**

            - id: comment-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/comments/**

            # SOCKET
            - id: notification-service-ws
              uri: ws://localhost:8082
              predicates:
                - Path=/notify/**
                - Header=Sec-WebSocket-Key, .+

            # REST
            - id: notification-service-http
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/notifications/**

            - id: hotel-admin
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/admin/**

            - id: hotel-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/hotels/**

            - id: booking-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/bookings/**