server:
  port: 8080

jwt:
  secret: 4UZslZIUa2bkHgxTGTACDPSKME0MxZDw

internal:
  secret:
    key: oO"kdug32^*Pg`9

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath*:public.pem
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/auth/**
            - id: comment-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/comments/**
            - id: hotel-admin
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/admin/**
            - id: hotel-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/hotels/**
            - id: booking-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/bookings/**