server:
  port: 8084

internal:
  secret:
    key: oO"kdug32^*Pg`9

comment:
  service_url: ${COMMENT_SERVICE_URL:http://localhost:8081}

spring:
  application:
    name: hotel-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hoteldb}
    username: ${SPRING_DATASOURCE_USERNAME:berkantgc}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always