server:
  port: 8084

internal:
  secret:
    key: oO"kdug32^*Pg`9

comment:
  service_url:
    http://localhost:8081

spring:
  application:
    name: hotel-service

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: berkantgc
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always