server:
  port: 8083

internal:
  secret:
    key: oO"kdug32^*Pg`9

aws:
  access_key_id: AKIA2UC3AZHRWLUON45M
  secret_access_key: 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
  region: eu-central-1
  bucket: hotelbookingse4458

spring:
  application:
    name: hotel-admin-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hoteldb}
    username: ${SPRING_DATASOURCE_USERNAME:berkantgc}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always